/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table fragment
	 */
	export class Fragment extends fragmentBase{

		//region Static
		//endregion

		//region Fields
		//endregion

		//region Private Methods
		//endregion

		//region Events
		//endregion

		//region Properties
		//endregion

	}
}