/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table group_user
	 */
	export class GroupUser extends groupUserBase{

		//region Static
		//endregion


		//region Fields
		//endregion


		//region Private Methods
		//endregion

		//region Methods
		/**
		 * Gets the metadata about the record
		 *
		 * @returns Object
		 */
		getMetadata(): IRecordMeta {
			return {
				fields: {
					idgroup: {
						text:  strings.group,
						type: 'record',
						recordType: 'Group',
						loaderFunction: Group.suggestionLoader()
					},
					iduser: {
						text:  strings.user,
						type: 'record',
						recordType: 'User',
						loaderFunction: User.suggestionLoader()
					}
				}
			}
		}
		//endregion


		//region Events
		//endregion


		//region Properties
        /**
         * Property field
         */
        private _user: User = null;

        /**
         * Gets or sets the user of the relationship
         *
         * @returns {User}
         */
        get user(): User {
            return this._user;
        }

        /**
         * Gets or sets the user of the relationship
         *
         * @param {User} value
         */
        set user(value: User) {
            this._user = value;
        }

        /**
         * Gets the users name
         *
         * @returns {string}
         */
        get userName(): string {
            return (this.user || new User()).toString();
        }

        /**
         * Gets the user attributes string
         *
         * @returns {string}
         */
        get userAttributes(): string {
            return (this.user || new User()).attributes;
        }


        //endregion

	}
}