/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table setting
	 */
	export class Setting extends settingBase{

		//region Static
		//endregion


		//region Fields
		//endregion


		//region Methods
		/**
		 * Gets the metadata about the record
		 *
		 * @returns Object
		 */
		getMetadata():IRecordMeta {
			return {
				fields: {
					value: {
						text: strings.settingValue,
						type: 'string'
					}
				}
			}
		}
		//endregion


		//region Events
		//endregion


		//region Properties
		//endregion

	}
}