version: '2'

services:
  webserver:
    image: fragment_local
    container_name: fragment_stateless_sqlite
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
#      - LOG_LEVEL=trace
      - FRAGMENT_DATA_DRIVER=sqlite
      - FRAGMENT_ROOT_PASSWORD=root