/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table card
	 */
	export class Card extends cardBase{

		//region Static
		//endregion


		//region Fields
		//endregion


		//region Private Methods
		//endregion


		//region Events
		//endregion


		//region Properties
		//endregion

	}
}