/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table cart
	 */
	export class Cart extends cartBase{

		//region Static
        /**
         * Prompts the CartView
         * @returns {any}
         */
        static prompt(){

            CartView.prompt();

            return void 0;
        }
		//endregion

		//region Fields
		//endregion

		//region Methods

		//endregion

		//region Events
		//endregion

		//region Properties
		//endregion

	}
}