/**
 * Generated by xlatte
 */
module latte{

    export interface ChargeOptions{
        amount: number;
        description?: string;
        flags?: number;
        callback?: (t: Transaction) => any;
    }

	/**
	 * Record for table charge
	 */
	export class Charge extends chargeBase{

		//region Static

		static FLAG_ADDRESS_NOT_NECESSARY = 8;

		/**
		 * Prompts the user to charge the specified amount
		 * @param amount
		 */
		static prompt(options: ChargeOptions){

		    let amount = options.amount;
            let description = options.description;
            let flags = options.flags || 0;
            let callback = options.callback;

			Charge.create(amount, description, flags).send((charge: Charge) => {

				CustomerView.prompt(charge, (customer: Customer, address: Address) => {
					log(customer);
					log(address);

					// Save collected data
					charge.idcustomer = customer.idcustomer;
					charge.customer = customer;

                    if(address) {
                        charge.idshippingaddress = address.idaddress;
                        charge.shippingAddress = address;
                    }

					// Save the changes on charge
					charge.save(() => {

                        // Go
						PaymentMethodView.prompt(charge, (t: Transaction) => {

						    if(callback) {
						        callback(t);
						    }

						});

					});
                });

				// if(c.isWalletSet) {
                //
				// 	c.wallet.driver.executeCharge(c);
                //
				// }else{
				// 	//TODO: Implement this
				// 	log("Charge.prompt: This flow part has not been implemented");
				// }

			});

		}
		//endregion


		//region Fields
		/**
		 * Customer of the charge
		 * @type {any}
		 */
		customer: Customer = null;

        /**
         * Billing address of the charge
         * @type {any}
         */
        billingAddress: Address = null;

		/**
		 * Shipping address of the charge
		 * @type {any}
		 */
		shippingAddress: Address = null;

		/**
		 * Wallet of the charge
		 * @type {any}
		 */
		wallet: Wallet = null;
		//endregion


		//region Private Methods
		//endregion


		//region Events
		//endregion


		//region Properties

		/**
		 * Gets a value indicating if the address is necessary
		 *
		 * @returns {boolean}
		 */
		get isNoShipping(): boolean {
			return (this.flags & Charge.FLAG_ADDRESS_NOT_NECESSARY) == Charge.FLAG_ADDRESS_NOT_NECESSARY;
		}

		/**
		 * Gets a value indicating if there is a customer on the charge
		 *
		 * @returns {boolean}
		 */
		get isCustomerSet(): boolean {
			return this.customer instanceof Customer;
		}

		/**
		 * Gets a value indicating if there is a wallet set on the charge
		 *
		 * @returns {boolean}
		 */
		get isWalletSet(): boolean {
			return this.wallet instanceof Wallet;
		}

		//endregion

	}
}