/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table customer
	 */
	export class Customer extends customerBase{

		//region Static
		//endregion

		//region Fields
		//endregion

		//region Private Methods
		//endregion

		//region Events
		//endregion

		//region Properties
		//endregion

	}
}