/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table PayMethod
	 */
	export class PayMethod extends paymethodBase{

		//region Static
		//endregion


		//region Fields
		wallet: Wallet = null;
		//endregion


		//region Private Methods
		//endregion


		//region Events
		//endregion


		//region Properties
		//endregion

	}
}