/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table payment
	 */
	export class Payment extends paymentBase{

		//region Static
        /**
         * Value to indicate if use sandboxing with payments engines
         * @type {boolean}
         */
        public static sandbox: boolean = true;

		//endregion

		//region Fields
		//endregion

		//region Private Methods
		//endregion

		//region Events
		//endregion

		//region Properties
		//endregion

	}
}