/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table transaction
	 */
	export class Transaction extends transactionBase{

		//region Static
		//endregion


		//region Fields
		//endregion


		//region Methods
		/**
		 * Gets the metadata about the record
		 *
		 * @returns Object
		 */
		getMetadata(): IRecordMeta {
			return {
				fields: {
					idcharge: {
						text: strings.charge,
						type: 'string',
						visible: 'if-not-inserted'
					},
					success: {
						text: strings.success,
						type: 'boolean'
					},
					created: {
						text: strings.created,
						type: 'datetime'
					},
					completed: {
						text: strings.completed,
						type: 'boolean'
					},
					mode: {
						text: strings.mode,
						type: 'enumeration',
                        options: [
                            '(None)',
                            strings.transOnDemand,
                            strings.transRest
                        ]
					},
					dataString: {
						text: strings.ticket,
						type: 'string'
					},
				}
			}
		}
		//endregion


		//region Events
		//endregion


		//region Properties
        /**
         * Gets the data as pretty json
         *
         * @returns {string}
         */
        get dataString(): string {
            return JSON.stringify(JSON.parse(this.data), null, 2);
        }

        //endregion

	}
}