/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table transaction
	 */
	export class Transaction extends transactionBase{

		//region Static
		//endregion


		//region Fields
		//endregion


		//region Private Methods
		//endregion


		//region Events
		//endregion


		//region Properties

		//endregion

	}
}