/**
 * Generated by xlatte
 */
module latte{

	/**
	 * Record for table wallet
	 */
	export class Wallet extends walletBase{

		//region Static
		//endregion


		//region Fields
		//endregion


		//region Methods
		//endregion


		//region Events
		//endregion


		//region Properties
		/**
		 * Field for driver property
		 */
		private _driver: WalletDriver;

		/**
		 * Gets the driver of the wallet
		 *
		 * @returns {WalletDriver}
		 */
		get driver(): WalletDriver {
			if (!this._driver) {
				if(this.driverua.length) {
					let f: any = latte[this.driverua];
					this._driver = new f();
				}else{
					throw sprintf("Driver <%s> not found", this.driver);
				}
			}
			return this._driver;
		}

		//endregion

	}
}