<?php
/**
 * Stub generated by xlatte
 */
class Group extends groupBase{

    /**
     * @return Group[]
     */
    public static function byUser($iduser){
        return DL::arrayOf('Group', "
            SELECT #COLUMNS
            FROM `group`
             INNER JOIN group_user USING (idgroup)
            WHERE group_user.iduser = '$iduser'
        ");
    }

    /**
     *
     * @remote
     * @return Group[]
     */
    public static function catalog(){
        return DL::arrayOf('Group', "
            SELECT #COLUMNS
            FROM `group`
        ");
    }

    /**
     * @remote
     * @param string $text
     * @return Group[]
     */
    public static function search($text){
        return DL::arrayOf('Group', "
            SELECT #COLUMNS
            FROM `group`
            WHERE name LIKE '$text%'
        ");
    }

}