<?php
/**
 * Stub generated by xlatte
 */
class GroupUser extends groupUserBase{

    /**
     * @remote
     * @param int $idgroup
     * @return GroupUser[]
     */
    public static function byGroup($idgroup){
        return DL::arrayOf('GroupUser,User', "
            SELECT #COLUMNS
            FROM group_user
             LEFT JOIN `user` USING (iduser)
            WHERE idgroup = '$idgroup'
        ");
    }

    /**
     * @var User
     */
    public $user;

}