<?php
/**
 * Stub generated by xlatte
 */
class CartPage extends cartpageBase{

    /**
     * @NeverRemote
     * @param int $idcart
     * @param int $idpage
     * @return CartPage
     */
    public static function byCartAndPage($idcart, $idpage){
        return DL::oneOf('CartPage', "
            SELECT #COLUMNS
            FROM cartPage
            WHERE idcart = '$idcart' AND idpage = '$idpage';
        ");
    }

}