<?php
/**
 * Stub generated by xlatte
 */
class Charge extends chargeBase{

    static $FLAG_ADDRESS_NOT_NECESSARY = 8;

    /**
     * @remote
     * @param int $page
     * @return PageResult<Charge>
     */
    public static function catalog($page = 1){
        return DL::pageOf('Charge', "
            SELECT #COLUMNS
            FROM charge
            ORDER BY created DESC
        ", $page);
    }

    /**
     * Creates the charge and returns it
     *
     * @remote
     * @param number $amount
     * @param string $description
     * @param int $flags
     * @return Charge
     */
    public static function create($amount, $description, $flags = 0){
        $c = new Charge();
        $c->description = $description;
        $c->amount = $amount;
        $c->flags = $flags;
        $c->insert();

        return $c;
    }

    /**
     * @var Wallet
     */
    public $wallet;

    public function onInserting(){
        $this->created = DL::dateTime();
    }

}