<?php
/**
 * Stub generated by xlatte
 */
class Customer extends customerBase{

    /**
     * @remote
     * @param int $page
     * @return PageResult<Customer>
     */
    public static function catalog($page = 1){
        return DL::pageOf('Customer', "
            SELECT #COLUMNS
            FROM customer
            ORDER BY idcustomer DESC
        ", $page);
    }

    /**
     * @remote
     * @param string $text
     * @return Customer[]
     */
    public static function search($text){
        return DL::arrayOf('Customer', "
            SELECT #COLUMNS
            FROM customer
            WHERE (firstname LIKE '%$text%' OR lastname LIKE '%$text%')
            ORDER BY firstname, lastname
        ");
    }

    public function onInserting(){
        $this->created = DL::dateTime();
    }

}