<?php
/**
 * Stub generated by xlatte
 */
class PayMethod extends paymethodBase{

    /**
     * Gets the publicly available wallets (Payment Methods)
     *
     * @remote
     * @return PayMethod[]
     */
    public static function getPublicAvailable(){
        return DL::arrayOf("PayMethod,Wallet", "
            SELECT #COLUMNS 
            FROM paymethod
             INNER JOIN wallet USING (idwallet)
            WHERE enabled = 1
        ");
    }

    /**
     * Wallet of method
     * @var Wallet
     */
    public $wallet;

}