<?php
/**
 * Stub generated by xlatte
 */
class Wallet extends walletBase{

    /**
     * Gets the wallet
     *
     * @remote
     * @param string $driver
     * @return Wallet
     * @throws Exception
     */
    public static function byDriver($driver){
        $d = DL::arrayOf('Wallet', "
      SELECT * 
      FROM wallet 
      WHERE driver = '$driver'
      AND enabled = 1
");

        if (sizeof($d) > 1){
            throw new Exception('More than one enabled driver of: ' . $driver);

        }else if (sizeof($d) < 1){
            throw new Exception('No enabled driver for: ' . $driver);
        }

        return $d[0];
    }

    /**
     * Gets the default wallet of the system.
     * Returns false if none.
     *
     * @remote
     * @return Wallet
     */
    public static function defaultWallet(){
        return DL::oneOf('Wallet', "
            SELECT *
            FROM wallet
            WHERE isdefault = 1
        ");
    }

    /**
     * Override
     * @return array
     */
    public function pack(){
        $arr = parent::pack();
        unset($arr['fields']['accountsecret']);
        unset($arr['fields']['datasecret']);
        return $arr;
    }

}